name: Run Monitor URL

on:
   workflow_dispatch:  # Manuel olarak çalıştırılabilir

jobs:
  run-script:
    runs-on: ubuntu-latest  # GitHub Actions'ı çalıştıracak ortam

    steps:
      # Python ortamını kuruyoruz
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python 3.x sürümünü kullanıyoruz

      # Gerekli bağımlılıkları yüklüyoruz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Reponun içeriğini çekiyoruz
      - name: Checkout repository
        uses: actions/checkout@v2

      # Python scriptini çalıştır ve dosyaya yaz
      - name: Run ana_domain.py and update file
        run: |
          python ana_domain.py > ana_link.txt  # Çıktıyı doğrudan dosyaya yaz

      # GitHub Actions'a yapılan değişiklikleri commit ediyoruz
      - name: Commit updated ana_link.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git pull  # Güncel değişiklikleri almak için
          
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add ana_link.txt
            git commit -m "Domain URL güncellendi."
            git push
          fi

      # mac-verileri.yml workflow'unu tetiklemek
      - name: Trigger mac-verileri.yml workflow
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/mac-verileri.yml/dispatches
