name: Run encode.py script

on:
  workflow_run:
    workflows: ["Run proxylive.py script"]
    types:
      - completed
  workflow_dispatch:  # Manuel çalıştırma

jobs:
  run_base_url_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run encode.py
        run: |
          python encode.py

      - name: Commit updated final_url.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git pull
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add final_url.txt
            git commit -m "İzle linkleri güncellendi."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger verileri-birlestir.yml workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/verileri-birlestir.yml/dispatches
