name: Run seolink.py script

on:
  workflow_run:
    workflows: ["Run mac-verisi.py script"]  # Ana Domain workflow'u tamamlandığında çalışacak
    types:
      - completed
  
jobs:
  run_base_url_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v3  # Daha güncel versiyon kullanıyoruz
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests

      - name: Run seolink.py and update file
        run: |
          python seolink.py > m3u_link.txt  # Çıktıyı doğrudan m3u_link.txt dosyasına yaz

      - name: Commit updated m3u_link.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git pull
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add m3u_link.txt
            git commit -m "M3U linkleri güncellendi."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # seolink.yml workflow'unu tetiklemek
      - name: Trigger m3u-link.yml workflow
        if: ${{ success() }}  # Bu adımdan önce başarılı olursa tetiklenir
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/m3u-link.yml/dispatches
