name: Run txt_to_m3u.py script

on:
  workflow_run:
    workflows: ["Run verileri_birlestir.py script"]
    types:
      - completed
  jobs:
  run_base_url_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run txt_to_m3u.py
        run: |
          python txt_to_m3u.py

      - name: Commit updated gol.m3u
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git pull
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add gol.m3u
            git commit -m "Tamamlandı."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
